name: cs2370
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0=py313hca03da5_0
  - anywidget=0.9.18=py313hca03da5_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - apricot-select=0.6.1=pyhd8ed1ab_2
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py313h254cc4a_0
  - array-api-compat=1.12.0=pyhe01879c_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=py313hca03da5_0
  - attrs=25.4.0=py313hca03da5_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h12fd690_2
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - babel=2.16.0=py313hca03da5_0
  - beautifulsoup4=4.13.5=py313hca03da5_0
  - biom-format=2.1.17=py313h9734d34_1
  - biothings_client=0.4.1=pyh29332c3_0
  - bleach=6.2.0=py313hca03da5_0
  - blinker=1.9.0=py313hca03da5_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - bottleneck=1.4.2=py313ha35b7ea_0
  - brotlipy=0.7.0=py313hcdf3177_1008
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.1=py313hca03da5_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py313hc845a76_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - choreographer=1.2.1=pyhcf101f3_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hc50a443_2
  - crc32c=2.8=py313h9734d34_0
  - cryptography=46.0.3=py313h4d9e278_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py313h6535dbc_1
  - dash=3.3.0=pyhd8ed1ab_0
  - dask=2025.10.0=pyhcf101f3_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2025.10.0=pyhcf101f3_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - flask=3.1.2=py313hca03da5_0
  - fonttools=4.60.1=py313h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - frozendict=2.4.6=py313haa24f5a_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - git-lfs=3.7.1=h07d3073_0
  - glog=0.7.1=heb240a5_0
  - h11=0.16.0=py313hca03da5_0
  - h5py=3.15.1=nompi_py313h7aa1c8b_100
  - hdf5=1.14.6=nompi_he65715a_103
  - httpcore=1.0.9=py313hca03da5_0
  - httpx=0.28.1=py313hca03da5_1
  - icu=73.2=hc8870d7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=py313hca03da5_0
  - itsdangerous=2.2.0=py313hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - json5=0.9.25=py313hca03da5_0
  - jsonschema=4.25.0=py313hca03da5_0
  - jsonschema-specifications=2023.7.1=py313hca03da5_0
  - jupyter-lsp=2.2.5=py313hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=py313hca03da5_0
  - jupyter_server=2.16.0=py313hca03da5_0
  - jupyter_server_terminals=0.5.3=py313hca03da5_0
  - jupyterlab=4.4.7=py313hca03da5_0
  - jupyterlab_pygments=0.3.0=py313hca03da5_0
  - jupyterlab_server=2.27.3=py313hca03da5_0
  - jupyterlab_widgets=3.0.15=py313hca03da5_0
  - kiwisolver=1.4.9=py313hf88c9ab_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libarrow=21.0.0=hd43feaf_8_cpu
  - libarrow-acero=21.0.0=hc317990_8_cpu
  - libarrow-compute=21.0.0=h75845d1_8_cpu
  - libarrow-dataset=21.0.0=hc317990_8_cpu
  - libarrow-substrait=21.0.0=h144af7f_8_cpu
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.9.0=37_hd9741b5_openblas
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_2
  - libopenjpeg=2.5.4=haa24f5a_0
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_8_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.08.12=h91c62da_1
  - libsodium=1.0.20=h99b78c6_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.7.1=cpu_generic_hd8f8d4b_4
  - libutf8proc=2.11.0=hc25f550_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.13.8=h0b34f26_0
  - libxslt=1.1.43=had6d056_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.4=h4a912ad_0
  - llvmlite=0.45.1=py313he297ed2_0
  - locket=1.0.0=pyhd8ed1ab_0
  - logistro=2.0.1=pyhcf101f3_0
  - lxml=5.3.0=py313h1d4350b_1
  - lz4=4.4.4=py313h975afc6_1
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib=3.10.7=py313h39782a4_0
  - matplotlib-base=3.10.7=py313h58042b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.2=py313hca03da5_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py313ha61f8ec_0
  - mygene=3.2.2=pyh5e36f6f_0
  - narwhals=2.10.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=py313hca03da5_0
  - nbconvert-core=7.16.6=py313hca03da5_0
  - nbformat=5.10.4=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=1.0=h5ca1d4c_0
  - nose=1.3.7=py_1006
  - notebook-shim=0.2.4=py313hca03da5_0
  - numba=0.62.1=py313h936dde2_0
  - numcodecs=0.16.1=py313h7d16b84_2
  - numexpr=2.14.1=py313h73ed539_0
  - numpy=2.3.4=py313h9771d21_0
  - openjpeg=2.5.4=h959fc53_0
  - openssl=3.6.0=h5503f6c_0
  - optree=0.17.0=py313hc50a443_1
  - orc=2.2.1=h4fd0076_0
  - orjson=3.11.4=py313h2c089d5_0
  - overrides=7.4.0=py313hca03da5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h6316d20_0
  - pandocfilters=1.5.1=py313hca03da5_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313h41ba818_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.1=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pomegranate=1.0.0=pyhd8ed1ab_3
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.21.1=py313hca03da5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py313h6535dbc_0
  - psygnal=0.12.0=py313hca03da5_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py313h39782a4_1
  - pyarrow-core=21.0.0=py313hb9a0e51_1_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyld=2.0.4=pyhd8ed1ab_1
  - pynndescent=0.5.13=py313hca03da5_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.1=pyhcf101f3_0
  - pytest-timeout=2.4.0=pyhd8ed1ab_0
  - python=3.13.9=hc7d8306_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.20.0=py313hca03da5_0
  - python-json-logger=3.2.1=py313hca03da5_0
  - python-kaleido=1.2.0=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=1_cp313
  - pytorch=2.7.1=cpu_generic_py313_heefb1e6_4
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py313h854a7ef_0
  - qhull=2020.2=h420ef59_5
  - re2=2025.08.12=h64b956e_1
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py313hca03da5_0
  - requests=2.32.5=py313hca03da5_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=py313hca03da5_0
  - rfc3986-validator=0.1.1=py313hca03da5_0
  - rpds-py=0.22.3=py313h2aea54e_0
  - scikit-allel=1.3.13=py313h668b085_2
  - scikit-bio=0.7.1=py313hc577518_1
  - scikit-learn=1.7.2=py313h6316d20_0
  - scipy=1.16.2=py313h0d10b07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py313hca03da5_1
  - setuptools=80.9.0=py313hca03da5_0
  - simplejson=3.20.2=py313h6535dbc_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.0=py313hca03da5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py313hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313hc577518_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.0.0=h48ca7d4_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=py313hca03da5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py313hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py313hcdf3177_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.9.post2=py313h8f79df9_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=py313hca03da5_2
  - websocket-client=1.8.0=py313hca03da5_0
  - werkzeug=3.1.3=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - widgetsnbextension=4.0.14=py313hca03da5_0
  - wrapt=1.17.0=py313h80987f9_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zarr=3.1.3=pyhcf101f3_0
  - zeromq=4.3.5=h888dc83_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - plotly-cloud==0.1.0
      - rich==14.2.0
      - tomli-w==1.2.0
prefix: /Users/skylarwalters/miniconda3/envs/cs2370
